"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vk-#%zi7nzlfrjv02fm_of0^h97v+z!4&8+rs@8#z95nf2x5qk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store', #django app
    'cart', #django app
    'mathfilters', #for math in template
    'account', #django app
    'crispy_forms', #extension for forms
    'payment', #django app

    

]

CRIPSY_TEMPLATE_PACK = 'bootstrap4' #improve quality of template


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages', #add view 
                'store.views.categories', #updated so we can access data across every template without explicit
                'cart.context_processors.cart',#we want to be able to see/access session data of our cart to see whats in it?
                
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
##connect static folder, tell where to connect to it
STATICFILES_DIRS = [BASE_DIR / 'static']
##STATICFILES_DIRS allows you to specify extra directories outside of the individual app directories where static 
## files are stored. This is useful for organizing static files that are shared across multiple apps or for including
##  static files from third-party libraries.

MEDIA_URL = '/media/'
#if you upload a file named example.jpg, it would be accessible via http://yourdomain.com/media/example.jpg
MEDIA_ROOT = BASE_DIR / 'static/media'
#MEDIA_ROOT is the filesystem path where uploaded files are stored on your server. It defines the directory where Django will save files that users upload through forms.
#need more defining in urls.py

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# email configuration settings, host email account
#need an app password
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' #instead of smtp console will receive email in console to test then escalate
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_USE_TLS = 'True'

EMAIL_HOST_USER = 'kedricklavigne@gmail.com' # - your email
EMAIL_HOST_PASSWORD = '' # - your password



SECURE_CROSS_ORIGIN_OPENER_POLICY='same-origin-allow-popups' #for paypal pop up     
